_config_powerline() {
	POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='15'
	POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='32'
	POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='234'
	POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='214'

	POWERLEVEL9K_USER_DEFAULT_FOREGROUND='15'
	POWERLEVEL9K_USER_DEFAULT_BACKGROUND='32'

	POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='15'
	POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='236'
	POWERLEVEL9K_DIR_HOME_FOREGROUND='15'
	POWERLEVEL9K_DIR_HOME_BACKGROUND='236'
	POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='15'
	POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='236'
	POWERLEVEL9K_DIR_ETC_FOREGROUND='15'
	POWERLEVEL9K_DIR_ETC_BACKGROUND='236'

	POWERLEVEL9K_STATUS_OK_FOREGROUND='28'
	POWERLEVEL9K_STATUS_OK_BACKGROUND='236'
	POWERLEVEL9K_STATUS_ERROR_FOREGROUND='15'
	POWERLEVEL9K_STATUS_ERROR_BACKGROUND='88'
}
